 
GET http://localhost:8080/tasks

###

GET http://localhost:8080/tasks/1
###
GET http://localhost:8080/tasks/2

###

POST http://localhost:8080/tasks
Content-Type: application/json

{
    "text" : "Temos de fazer o trabalho de PI"
}